// examples/saas-sveltekit/src/lib/components/ui/StatusBadge.svelte
<script lang="ts">
	import type { InvoiceStatusValue } from '$lib/schemas/invoice';

	// --- R2: Pure UI, data via props ---
	// --- Svelte 5 runes ---
	let { status }: { status: InvoiceStatusValue } = $props();

	const variants: Record<InvoiceStatusValue, string> = {
		draft: 'bg-muted text-muted-foreground',
		sent: 'bg-primary/10 text-primary',
		paid: 'bg-success/10 text-success',
		overdue: 'bg-destructive/10 text-destructive',
		cancelled: 'bg-muted text-muted-foreground line-through'
	};

	const labels: Record<InvoiceStatusValue, string> = {
		draft: 'Draft',
		sent: 'Sent',
		paid: 'Paid',
		overdue: 'Overdue',
		cancelled: 'Cancelled'
	};
</script>

<span class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium {variants[status]}">
	{labels[status]}
</span>

// examples/saas-nextjs/components/ui/status-badge.tsx
/**
 * Shared UI component — can be imported by any feature (R5 exception for ui/).
 * Semantic tokens only — no hardcoded Tailwind colors.
 */

const StatusConfig = {
  draft: { label: 'Draft', className: 'bg-muted text-muted-foreground' },
  sent: { label: 'Sent', className: 'bg-primary/10 text-primary' },
  paid: { label: 'Paid', className: 'bg-accent text-accent-foreground' },
  overdue: { label: 'Overdue', className: 'bg-destructive/10 text-destructive' },
  cancelled: { label: 'Cancelled', className: 'bg-muted text-muted-foreground line-through' },
} as const // R8 — zero magic strings

type Props = {
  status: keyof typeof StatusConfig
}

export function StatusBadge({ status }: Props) {
  const config = StatusConfig[status]

  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${config.className}`}
    >
      {config.label}
    </span>
  )
}
