// examples/saas-sveltekit/src/routes/dashboard/invoices/+page.svelte
<script lang="ts">
	import InvoiceList from '$lib/components/invoices/InvoiceList.svelte';
	import InvoiceForm from '$lib/components/invoices/InvoiceForm.svelte';

	// --- Data from +page.server.ts load function ---
	let { data, form } = $props();

	let showForm = $state(false);
</script>

<svelte:head>
	<title>Invoices | InvoiceFlow</title>
</svelte:head>

<div class="mx-auto max-w-5xl space-y-6 p-6">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold text-foreground">Invoices</h1>
		<button
			onclick={() => (showForm = !showForm)}
			class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
		>
			{showForm ? 'Cancel' : 'New Invoice'}
		</button>
	</div>

	{#if form?.success}
		<div class="rounded-md bg-success/10 px-4 py-3 text-sm text-success">
			Invoice created successfully.
		</div>
	{/if}

	{#if data.error}
		<div class="rounded-md bg-destructive/10 px-4 py-3 text-sm text-destructive">
			{data.error}
		</div>
	{/if}

	{#if showForm}
		<div class="rounded-lg border border-border bg-card p-6">
			<h2 class="mb-4 text-lg font-semibold text-card-foreground">Create Invoice</h2>
			<InvoiceForm errors={form?.errors ?? {}} />
		</div>
	{/if}

	<InvoiceList invoices={data.invoices} />
</div>

// examples/saas-nextjs/app/dashboard/invoices/page.tsx
/**
 * Invoices page — Server Component by default (R6).
 * Fetches data via lib/queries, passes to pure UI components (R1, R2).
 * No 'use client' — server-rendered.
 */

import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getInvoices } from '@/lib/queries/invoices'
import { InvoiceListClient } from '@/app/dashboard/invoices/invoice-list-client'

export default async function InvoicesPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    redirect('/login')
  }

  const result = await getInvoices(user.id)

  if (!result.success) {
    return (
      <div className="p-6">
        <p className="text-destructive">Failed to load invoices.</p>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-foreground">Invoices</h1>
      </div>
      <InvoiceListClient invoices={result.data} />
    </div>
  )
}
